### ISSUE TITLE
More items to be added in application inventory filter list

### ISSUE THREAD

**Issue by sshveta** [konveyor/tackle#4]
This might be in progress so just a placeholder bug .

![Screenshot from 2021-03-25 14-33-17](https://user-images.githubusercontent.com/3866976/112546991-66c8ea80-8d77-11eb-9329-294c285ce90e.png)
 

As mentioned in https://issues.redhat.com/browse/TACKLE-8

In Application Inventory page : 
"The list must be filterable by Name, Description, Business Service, Tag, Assessment status, Review status and Tag count. Comments is not a filterable field."

**Comment by mrizzi** [comment]
@sshveta that's right.
So far we can add only Description and Business Service filtering (since we have no other columns):

- Description is in https://github.com/konveyor/tackle-ui/issues/68
- Business service is in https://github.com/konveyor/tackle-ui/issues/51

I close this issue because we will keep trace of the work to be done in the issues mentioned above.
